### ISSUE TITLE
The json vat rates api seems to be discontinued.

### ISSUE THREAD

**Issue by wout** [VvanGemert/europe.cr#4]
Unfortunately, the jsonvat.com project is no longer:
https://github.com/adamcooke/vat-rates

Are you planning to implement scraping just like it's done in the ruby variant of this shard?

**Comment by VvanGemert** [comment]
This is fixed in latest release v0.1.11. Using a different endpoint. I will have a look into another more stable endpoint, preferably from the EU itself. Thanks for heads up!

**Comment by wout** [comment]
Excellent, thanks!
