### ISSUE TITLE
Typo in v0.1.12 version

### ISSUE THREAD

**Issue by wout** [VvanGemert/europe.cr#5]
There's a typo in the latest tag:

![image](https://user-images.githubusercontent.com/107324/81090291-67555a00-8ef5-11ea-936b-ae1a5b162544.png)

Which results in version resolve error while installing:

![image](https://user-images.githubusercontent.com/107324/81090406-979cf880-8ef5-11ea-9997-73aae6152d5f.png)

**Comment by VvanGemert** [comment]
Thank @wout. Fixed it and bumped to v0.1.13
